services:
  postgres:
    image: postgres:16
    container_name: smt-postgres
    environment:
      POSTGRES_DB: stock_market_tracker
      POSTGRES_USER: nahim
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: